name: Main e2e tests

on:
  push:
    branches: [ develop, master ]
  pull_request:
    branches: [ develop, master ]
  workflow_dispatch:

jobs:
  main-e2e:
    name: Main frontend e2e tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run Main e2e tests
        run: docker-compose -f ./docker/main-test/docker-compose.main-test.yml up --build --exit-code-from cypress
